language: node_js
sudo: false
node_js:
- '7'
cache: yarn
before_script:
- yarn install
script:
- yarn run build-css
- yarn run build-dist-js
- echo "node_modules" > .gitignore

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages # gh-pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master
