var f="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},h="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function k(){k=function(){};h.Symbol||(h.Symbol=aa)}var ba=0;function aa(a){return"jscomp_symbol_"+(a||"")+ba++}
function n(){k();var a=h.Symbol.iterator;a||(a=h.Symbol.iterator=h.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&f(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return p(this)}});n=function(){}}function p(a){var b=0;return ca(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ca(a){n();a={next:a};a[h.Symbol.iterator]=function(){return this};return a}function q(a){n();k();n();var b=a[Symbol.iterator];return b?b.call(a):p(a)}
for(var r=h,t=["Promise"],u=0;u<t.length-1;u++){var v=t[u];v in r||(r[v]={});r=r[v]}
var x=t[t.length-1],y=r[x],z=function(){function a(a){this.b=0;this.j=void 0;this.a=[];var b=this.f();try{a(b.resolve,b.reject)}catch(m){b.reject(m)}}function b(){this.a=null}function c(b){return b instanceof a?b:new a(function(a){a(b)})}if(y)return y;b.prototype.b=function(a){this.a||(this.a=[],this.i());this.a.push(a)};b.prototype.i=function(){var a=this;this.f(function(){a.s()})};var d=h.setTimeout;b.prototype.f=function(a){d(a,0)};b.prototype.s=function(){for(;this.a&&this.a.length;){var a=this.a;
this.a=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(w){this.j(w)}}}this.a=null};b.prototype.j=function(a){this.f(function(){throw a;})};a.prototype.f=function(){function a(a){return function(g){c||(c=!0,a.call(b,g))}}var b=this,c=!1;return{resolve:a(this.H),reject:a(this.i)}};a.prototype.H=function(b){if(b===this)this.i(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof a)this.I(b);else{a:switch(typeof b){case "object":var c=null!=b;break a;case "function":c=
!0;break a;default:c=!1}c?this.G(b):this.s(b)}};a.prototype.G=function(a){var b=void 0;try{b=a.then}catch(m){this.i(m);return}"function"==typeof b?this.J(b,a):this.s(a)};a.prototype.i=function(a){this.A(2,a)};a.prototype.s=function(a){this.A(1,a)};a.prototype.A=function(a,b){if(0!=this.b)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.b);this.b=a;this.j=b;this.F()};a.prototype.F=function(){if(this.a){for(var a=this.a,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.a=
null}};var e=new b;a.prototype.I=function(a){var b=this.f();a.o(b.resolve,b.reject)};a.prototype.J=function(a,b){var c=this.f();try{a.call(b,c.resolve,c.reject)}catch(w){c.reject(w)}};a.prototype.then=function(b,c){function d(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(ka){g(ka)}}:b}var e,g,l=new a(function(a,b){e=a;g=b});this.o(d(b,e),d(c,g));return l};a.prototype.catch=function(a){return this.then(void 0,a)};a.prototype.o=function(a,b){function c(){switch(d.b){case 1:a(d.j);break;
case 2:b(d.j);break;default:throw Error("Unexpected state: "+d.b);}}var d=this;this.a?this.a.push(function(){e.b(c)}):e.b(c)};a.resolve=c;a.reject=function(b){return new a(function(a,c){c(b)})};a.race=function(b){return new a(function(a,d){for(var e=q(b),g=e.next();!g.done;g=e.next())c(g.value).o(a,d)})};a.all=function(b){var d=q(b),e=d.next();return e.done?c([]):new a(function(a,b){function g(b){return function(c){l[b]=c;m--;m||a(l)}}var l=[],m=0;do l.push(void 0),m++,c(e.value).o(g(l.length-1),
b),e=d.next();while(!e.done)})};return a}();z!=y&&null!=z&&f(r,x,{configurable:!0,writable:!0,value:z});"serviceWorker"in navigator&&(navigator.serviceWorker.register("./sw.js").then(function(){console.log("service worker is all cool.")}).catch(function(a){console.error("service worker is not so cool.",a);throw a;}),navigator.serviceWorker.controller&&(navigator.serviceWorker.controller.onstatechange=function(a){"redundant"===a.target.state&&document.querySelector("#reload-prompt").classList.remove("hidden")}));
var A="onpointerdown"in document.createElement("div"),B=0,C=new ("undefined"!==typeof webkitAudioContext?webkitAudioContext:AudioContext),D=C.createGain();D.connect(C.destination);
var E=["#781c81","#447cbf","#83ba6d","#dbab3b","#d92120"],F={c:!1,w:[{name:"Beto Cruz",g:41},{name:"Martin Spasiuk",g:103},{name:"Lucho Gomez",g:45},{name:"Gera  Massenzano",g:4},{name:"Maxi Guillen",g:33}],D:window.localStorage.getItem("fidget_spinner")||"./assets/spinners/arrow.png",muted:"true"===window.localStorage.getItem("fidget_muted")?!0:!1,m:window.localStorage.getItem("fidget_spins")?parseInt(window.localStorage.getItem("fidget_spins"),10):0,l:window.localStorage.getItem("fidget_max_velocity")?
parseInt(window.localStorage.getItem("fidget_max_velocity"),10):0},da=[{path:"./assets/spinners/arrow.png",name:"The Classic",h:0},{path:"./assets/spinners/triple.png",name:"The Triple",h:500},{path:"./assets/spinners/pokeball.png",name:"The 'Chu",h:2E3},{path:"./assets/spinners/cube.png",name:"The Cubist",h:5E3},{path:"./assets/spinners/fractal.png",name:"The Fractal",h:1E4}],ea=document.getElementById("turns"),fa=document.getElementById("velocity"),ga=document.getElementById("maxVelocity"),G=document.getElementById("spinner"),
ha=document.getElementById("trace-slow"),ia=document.getElementById("trace-fast"),H=document.getElementById("toggle-audio"),ja=Array.from(document.getElementsByClassName("spinner")),la=document.getElementById("picker"),I=document.getElementById("spinner-picker"),J=0,K=0,L=null;function M(a){"undefined"!==typeof requestIdleCallback?requestIdleCallback(a,{timeout:60}):"undefined"!==typeof requestAnimationFrame?requestAnimationFrame(a):setTimeout(a,16.66)}
function ma(){B=Math.abs(3600*K/2/Math.PI)|0;var a=Math.max(B,F.l);F.l!==a&&(M(function(){return window.localStorage.setItem("fidget_max_velocity",""+F.l)}),F.l=a);F.m+=Math.abs(K/2/Math.PI);M(function(){return window.localStorage.setItem("fidget_spins",""+F.m)});a=F.l.toLocaleString(void 0,{maximumFractionDigits:1});ea.textContent=""+F.m.toLocaleString(void 0,{maximumFractionDigits:0});fa.textContent=""+B;ga.textContent=""+a}
var N=G.getBoundingClientRect(),na=N.left+N.width/2,oa=N.top+N.height/2,O=N.width/10,P=0,Q=0,R=!1,S=0,T=0;function U(a){return{x:("touches"in a?a.touches[0].clientX:a.clientX)-na,y:("touches"in a?a.touches[0].clientY:a.clientY)-oa}}function pa(a){if(!F.c){var b=U(a),c=b.x,b=b.y;V(a);R=!0;Q=Math.sqrt(Math.pow(c,2)+Math.pow(b,2));T=P}}function V(a){if(!F.c){var b=U(a);P=Math.atan2(b.x,b.y);a.preventDefault()}}function W(){F.c||(R=!1)}
function X(){requestAnimationFrame(function(){var a=K;R?(L=null,Q>O&&(S=P-T,S<-Math.PI&&(S+=2*Math.PI),S>Math.PI&&(S-=2*Math.PI),K=S,T=P)):S&&(K=S*Q/O,S=0);J-=K;G.style.transform="rotate("+J+"rad)";ha.style.opacity=.2<Math.abs(K)?"1":"0.00001";ia.style.opacity=.4<Math.abs(K)?"1":"0.00001";ma();K*=.99;K=Math.sign(K)*Math.max(0,Math.abs(K)-2E-4);if(!R&&!K&&0!==a){L=J%(2*Math.PI);console.log("winner",L);a:{for(var b=L,a=qa(),c=ra(),b=b/(2*Math.PI),d=0,e=0;e<a.length;e++)if(d+=a[e],b<=d){a=c[e];break a}a=
"WTF"}alert("And the winner is... "+a)}if((a=Math.abs(B*Math.PI/60))&&!R){var e=a,c=C.currentTime,g=e,e=Math.min(1,e/10);c+(e*(2-e)*1.1-(.6-.6*e*(2-e)))-e*(2-e)<Y||(b=C.createOscillator(),d=C.createGain(),e=Math.min(1,Math.max(0,e)),b.type="triangle",b.connect(d),d.connect(D),g=sa(g),e=.1*(1-e/2),b.frequency.setValueAtTime(g,c),b.frequency.linearRampToValueAtTime(1.8*g,c+=e),Y=c+e,d.gain.setValueAtTime(.1,C.currentTime),d.gain.linearRampToValueAtTime(0,Y),b.start(C.currentTime),b.stop(Y));d=a;a=C.currentTime;
e=d;d=Math.min(1,d/10);a+(d*(2-d)*1.1-(.3-.3*d*(2-d)))-d*(2-d)<Z||(c=C.createOscillator(),b=C.createGain(),d=Math.min(1,Math.max(0,d)),c.type="sine",c.connect(b),b.connect(D),e=ta(e),d=.05*(1-d/2),c.frequency.setValueAtTime(e,a),c.frequency.linearRampToValueAtTime(1.8*e,a+=d),Z=a+d,b.gain.setValueAtTime(.15,C.currentTime),b.gain.linearRampToValueAtTime(0,Z),c.start(C.currentTime),c.stop(Z))}X()})}var Y=-1,Z=-1;function ua(a){return function(b){return a.v+(b-a.u)/(a.B-a.u)*(a.C-a.v)}}
var sa=ua({u:0,B:80,v:400,C:2E3}),ta=ua({u:0,B:80,v:300,C:1500});function va(){function a(){var b=C.createBufferSource();b.buffer=C.createBuffer(1,1,22050);b.connect(C.destination);"undefined"===typeof b.start?b.noteOn(0):b.start(0);b.onended=function(){b.disconnect(0);document.removeEventListener("touchend",a,!0)}}document.addEventListener("touchend",a,!0)}
function wa(){H.classList.toggle("muted",F.muted);D.gain.setValueAtTime(F.muted?0:1,C.currentTime);window.localStorage.setItem("fidget_muted",""+F.muted)}function xa(){!0!==F.c?(F.c=!F.c,history.pushState(F,"","#picker"),ya()):history.back()}function za(a){F.muted=!F.muted;wa();a.stopPropagation()}function Aa(a){F.D=a;M(function(){return window.localStorage.setItem("fidget_spinner",a)});for(var b=q(ja),c=b.next();!c.done;c=b.next())c.value.src=a}
function Ba(a){var b=a.target;"IMG"!==b.tagName||b.classList.contains("locked")||(Aa(a.target.src),xa())}function ya(){for(var a=I.innerHTML="",b=q(da),c=b.next();!c.done;c=b.next())c=c.value,a+='<li><p class="title">'+c.name+"</p>",a=c.h>=F.m?a+('<img width="300" height="300" class="locked" src="'+c.path+'"><p class="locked-info">Unlocks at '+c.h+" spins</p>"):a+('<img width="300" height="300" src="'+c.path+'">'),a+="</li>";I.innerHTML=a;I.classList.remove("hidden");I.scrollTop=0}
function Ca(){var a=qa(),b=0,c=document.querySelector("#wheel-container svg");c?a.length>E.length?console.error("We need more colors!"):a.forEach(function(a,e){var d=q([Math.cos(2*Math.PI*b),Math.sin(2*Math.PI*b)]),l=d.next().value,d=d.next().value;b+=a;var m=q([Math.cos(2*Math.PI*b),Math.sin(2*Math.PI*b)]),w=m.next().value,m=m.next().value;a=["M "+l+" "+d,"A 1 1 0 "+(.5<a?1:0)+" 1 "+w+" "+m,"L 0 0"].join(" ");l=document.createElementNS("http://www.w3.org/2000/svg","path");l.setAttribute("d",a);l.setAttribute("fill",
E[e]);c.appendChild(l)}):console.error("Missing svg element")}function Da(){var a=ra(),b=document.querySelector("#participants");b?a.map(function(a,b){var c=document.createElement("div");c.style.borderColor=E[b];c.innerText=a;return c}).forEach(function(a){return b.appendChild(a)}):console.error("Missing #participants element")}function qa(){var a=F.w.reduce(function(a,c){return a+c.g},0);return F.w.map(function(b){return b.g/a})}function ra(){return F.w.map(function(a){return a.name})}
(function(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(d,e){function g(a){a.done?d(a.value):Promise.resolve(a.value).then(b,c).then(g,e)}g(a.next())})})(function(){function a(){for(;;)switch(b){case 0:Ca(),Da(),wa(),va(),X(),c=document.addEventListener,la.addEventListener(A?"pointerdown":"touchstart",xa),I.addEventListener("click",Ba),H.addEventListener(A?"pointerdown":"touchstart",za),c(A?"pointerdown":"touchstart",pa,{passive:!1}),c(A?"pointermove":
"touchmove",V,{passive:!1}),c(A?"pointerup":"touchend",W),c(A?"pointercancel":"touchcancel",W),history.replaceState(null,"","/"),Aa(F.D),window.onpopstate=function(a){null===a.state?(F.c=!1,I.classList.add("hidden")):null!==a.state&&(F.c=!0,ya())},b=-1;default:return{value:void 0,done:!0}}}var b=0,c,d={next:function(){return a()},throw:function(){return a()},return:function(){throw Error("Not yet implemented");}};n();d[Symbol.iterator]=function(){return this};return d}());
